// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jsongrpc.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JsonRequest struct {
	D1                   []byte   `protobuf:"bytes,1,opt,name=D1,proto3" json:"D1,omitempty"`
	D2                   []byte   `protobuf:"bytes,2,opt,name=D2,proto3" json:"D2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JsonRequest) Reset()         { *m = JsonRequest{} }
func (m *JsonRequest) String() string { return proto.CompactTextString(m) }
func (*JsonRequest) ProtoMessage()    {}
func (*JsonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f3b87a3105af75e, []int{0}
}

func (m *JsonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JsonRequest.Unmarshal(m, b)
}
func (m *JsonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JsonRequest.Marshal(b, m, deterministic)
}
func (m *JsonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JsonRequest.Merge(m, src)
}
func (m *JsonRequest) XXX_Size() int {
	return xxx_messageInfo_JsonRequest.Size(m)
}
func (m *JsonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JsonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JsonRequest proto.InternalMessageInfo

func (m *JsonRequest) GetD1() []byte {
	if m != nil {
		return m.D1
	}
	return nil
}

func (m *JsonRequest) GetD2() []byte {
	if m != nil {
		return m.D2
	}
	return nil
}

type JsonReply struct {
	COMB                 []byte   `protobuf:"bytes,1,opt,name=COMB,proto3" json:"COMB,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JsonReply) Reset()         { *m = JsonReply{} }
func (m *JsonReply) String() string { return proto.CompactTextString(m) }
func (*JsonReply) ProtoMessage()    {}
func (*JsonReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f3b87a3105af75e, []int{1}
}

func (m *JsonReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JsonReply.Unmarshal(m, b)
}
func (m *JsonReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JsonReply.Marshal(b, m, deterministic)
}
func (m *JsonReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JsonReply.Merge(m, src)
}
func (m *JsonReply) XXX_Size() int {
	return xxx_messageInfo_JsonReply.Size(m)
}
func (m *JsonReply) XXX_DiscardUnknown() {
	xxx_messageInfo_JsonReply.DiscardUnknown(m)
}

var xxx_messageInfo_JsonReply proto.InternalMessageInfo

func (m *JsonReply) GetCOMB() []byte {
	if m != nil {
		return m.COMB
	}
	return nil
}

func init() {
	proto.RegisterType((*JsonRequest)(nil), "protobuf.JsonRequest")
	proto.RegisterType((*JsonReply)(nil), "protobuf.JsonReply")
}

func init() { proto.RegisterFile("jsongrpc.proto", fileDescriptor_3f3b87a3105af75e) }

var fileDescriptor_3f3b87a3105af75e = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x2a, 0xce, 0xcf,
	0x4b, 0x2f, 0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5,
	0x69, 0x4a, 0xba, 0x5c, 0xdc, 0x5e, 0xc5, 0xf9, 0x79, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25,
	0x42, 0x7c, 0x5c, 0x4c, 0x2e, 0x86, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x4c, 0x2e, 0x86,
	0x60, 0xbe, 0x91, 0x04, 0x13, 0x94, 0x6f, 0xa4, 0x24, 0xcf, 0xc5, 0x09, 0x51, 0x5e, 0x90, 0x53,
	0x29, 0x24, 0xc4, 0xc5, 0xe2, 0xec, 0xef, 0xeb, 0x04, 0x55, 0x0e, 0x66, 0x1b, 0xb9, 0x70, 0x71,
	0x80, 0xec, 0x4a, 0xce, 0xcf, 0x2b, 0x13, 0xb2, 0xe0, 0xe2, 0x28, 0xc8, 0x49, 0xac, 0x04, 0xf1,
	0x85, 0x44, 0xf5, 0x60, 0x56, 0xea, 0x21, 0xd9, 0x27, 0x25, 0x8c, 0x2e, 0x5c, 0x90, 0x53, 0xa9,
	0xc4, 0xe0, 0x64, 0xc0, 0x25, 0x9d, 0x99, 0xaf, 0x07, 0x76, 0x70, 0x6a, 0x45, 0x62, 0x6e, 0x41,
	0x4e, 0x6a, 0xb1, 0x5e, 0x46, 0x6a, 0x4e, 0x4e, 0x7e, 0x79, 0x7e, 0x51, 0x4e, 0x8a, 0x13, 0xbf,
	0x07, 0x88, 0x1d, 0x0e, 0x62, 0x07, 0x80, 0xb4, 0x07, 0x30, 0x26, 0xb1, 0x81, 0xcd, 0x31, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x82, 0x9a, 0x95, 0xea, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JsonconvClient is the client API for Jsonconv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JsonconvClient interface {
	Playjson(ctx context.Context, in *JsonRequest, opts ...grpc.CallOption) (*JsonReply, error)
}

type jsonconvClient struct {
	cc *grpc.ClientConn
}

func NewJsonconvClient(cc *grpc.ClientConn) JsonconvClient {
	return &jsonconvClient{cc}
}

func (c *jsonconvClient) Playjson(ctx context.Context, in *JsonRequest, opts ...grpc.CallOption) (*JsonReply, error) {
	out := new(JsonReply)
	err := c.cc.Invoke(ctx, "/protobuf.jsonconv/playjson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JsonconvServer is the server API for Jsonconv service.
type JsonconvServer interface {
	Playjson(context.Context, *JsonRequest) (*JsonReply, error)
}

// UnimplementedJsonconvServer can be embedded to have forward compatible implementations.
type UnimplementedJsonconvServer struct {
}

func (*UnimplementedJsonconvServer) Playjson(ctx context.Context, req *JsonRequest) (*JsonReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Playjson not implemented")
}

func RegisterJsonconvServer(s *grpc.Server, srv JsonconvServer) {
	s.RegisterService(&_Jsonconv_serviceDesc, srv)
}

func _Jsonconv_Playjson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JsonconvServer).Playjson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.jsonconv/Playjson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JsonconvServer).Playjson(ctx, req.(*JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Jsonconv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.jsonconv",
	HandlerType: (*JsonconvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "playjson",
			Handler:    _Jsonconv_Playjson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jsongrpc.proto",
}
